import { useState, useMemo, useEffect } from "react";
import { formatValue, generateMockMarketCapData } from "../../../utils/utils";
import { useStockPageData } from "../../../hooks/useStockPageData";
import StatisticPageLayout from "../../../components/StatisticPageLayout";
import LineChart from "../../../components/Chart/LineChart";
import { useParams } from "react-router-dom";
import { getRelatedStocks } from "../../../lib/data";

export default function Revenue() {
    const { id } = useParams<{ id: string }>();
    const { info, stats, isLoading: isLoadingMain } = useStockPageData();
    const [isRelatedLoading, setIsRelatedLoading] = useState(true);
    const [selectedRange, setSelectedRange] = useState("1M");
    const [relatedStocks, setRelatedStocks] = useState<any[]>([]);

    const ranges = ["1M", "6M", "YTD", "1Y", "3Y", "5Y"];

    const mockChartData = useMemo(() => {
        return generateMockMarketCapData(selectedRange);
    }, [selectedRange]);

    useEffect(() => {
        const fetchRelated = async () => {
            if (!id) return;
            try {
                setIsRelatedLoading(true);
                const relatedStocksData = await getRelatedStocks(Number(id));
                setRelatedStocks(relatedStocksData);
            } catch (err) {
                console.error("Failed to fetch related stocks:", err);
            } finally {
                setIsRelatedLoading(false);
            }
        };

        fetchRelated();
    }, [id]);

    if (isLoadingMain || isRelatedLoading) {
        return (
            <div className="flex items-center justify-center p-20">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500"></div>
            </div>
        );
    }

    const symbol = info?.symbol || "Unknown";
    const name = info?.name || "this stock";
    const revenueFormatted = formatValue(stats?.revenue_ttm);

    const historyData = [
        { date: "Dec 31, 2025", value: "3.55T", change: "20.5%", positive: true },
        { date: "Dec 31, 2024", value: "2.95T", change: "15.2%", positive: true },
        { date: "Dec 31, 2023", value: "2.56T", change: "12.8%", positive: true },
        { date: "Dec 31, 2022", value: "2.27T", change: "8.5%", positive: true },
        { date: "Dec 31, 2021", value: "2.09T", change: "-2.1%", positive: false },
    ];

    const relatedStocksFormatted = relatedStocks?.map((stock) => ({
        name: stock?.symbol || "Unknown",
        value: formatValue(stock?.revenue_ttm),
    }));

    return (
        <StatisticPageLayout
            symbol={`NGX:${symbol}`}
            description={`${symbol}:${name} generated ${revenueFormatted} in revenue (TTM). This section provides details on revenue growth and profitability metrics.`}
            headerStats={[
                { label: "Revenue (TTM)", value: revenueFormatted },
                { label: "Net Income", value: formatValue(stats?.net_income) },
                { label: "EPS", value: formatValue(stats?.eps) },
                { label: "Shares Outstanding", value: formatValue(stats?.shares_outstanding) },
                { label: "Market Cap", value: formatValue(stats?.market_cap) },
                { label: "PE Ratio", value: formatValue(stats?.pe_ratio) },
            ]}
            sidebarTitle="Revenue & Profitability"
            sidebarText="Revenue is the total amount of income generated by the sale of goods or services related to the company's primary operations. Net income is the profit remaining after all expenses and taxes have been paid."
            chartTitle="Revenue Chart"
            chartComponent={<LineChart
                labels={mockChartData.labels}
                data={mockChartData.data}
                lineColor="#1a5b81"
                fillColor="rgba(26, 91, 129, 0.05)"
                height={400}
            />}
            selectedRange={selectedRange}
            onRangeChange={setSelectedRange}
            ranges={ranges}
            summaryText={
                <>
                    In the last 12 months, <span className="font-bold">NGX:${symbol}</span> had revenue of {revenueFormatted} and net income of {formatValue(stats?.net_income)}. This represents a <span className="text-emerald-600 font-bold">15.4%</span> increase in revenue compared to the previous year.
                </>
            }
            relatedStocks={relatedStocksFormatted}
            relatedStocksTitle="Related Stocks by Revenue"
            historyTitle="Revenue History"
            historyData={historyData}
            historyValueLabel="Revenue"
        />
    );
}
